#!/bin/bash

yabai -m 'config' 'mouse_modifier'             'alt'
yabai -m 'config' 'layout'                     'bsp'
yabai -m 'config' 'window_border'              'on'
yabai -m 'config' 'window_border_width'        4
yabai -m 'config' 'window_gap'                 16
yabai -m 'config' 'top_padding'                8
yabai -m 'config' 'bottom_padding'             8
yabai -m 'config' 'left_padding'               8
yabai -m 'config' 'right_padding'              8
yabai -m 'config' 'active_window_border_color' '0xffb8bb26'
yabai -m 'config' 'normal_window_border_color' '0xff79740e'

yabai -m rule --add 'app=^System Preferences$' 'manage=off'

yabai -m signal --add 'event=window_destroyed'   'action=yabai -m window --focus first'
# yabai -m signal --add 'event=window_minimized'   'action=yabai -m window --focus first'
yabai -m signal --add 'event=application_hidden' 'action=yabai -m window --focus first'
